### ISSUE TITLE
[Bug]: New problem to download

### ISSUE THREAD

**Issue by eliottp1089** [Puyodead1/udemy-downloader#106]
### What happened?

The script give this error:

[01:04:26] [udemy-downloader] [parse_new:1411] INFO: Chapter(s) (13)
[01:04:26] [udemy-downloader] [parse_new:1412] INFO: Lecture(s) (153)
[01:04:26] [udemy-downloader] [parse_new:1426] INFO: ======= Processing chapter 1 of 13 =======
[01:04:26] [udemy-downloader] [parse_new:1444] INFO:   > Processing lecture 1 of 153
[01:04:26] [udemy-downloader] [parse_new:1449] INFO:       > Lecture '001 Introducción' is already downloaded, skipping...
[01:04:26] [udemy-downloader] [parse_new:1485] INFO:     > Processing 0 asset(s) for lecture...
[01:04:26] [udemy-downloader] [parse_new:1444] INFO:   > Processing lecture 2 of 153
[01:04:26] [udemy-downloader] [parse_new:1449] INFO:       > Lecture '002 ¿Cómo funcionará el curso' is already downloaded, skipping...
[01:04:26] [udemy-downloader] [parse_new:1485] INFO:     > Processing 0 asset(s) for lecture...
[01:04:26] [udemy-downloader] [parse_new:1444] INFO:   > Processing lecture 3 of 153
[01:04:26] [udemy-downloader] [process_lecture:1346] INFO:       > Lecture '003 ¿Cómo realizar preguntas' has DRM, attempting to download
[01:04:26] [udemy-downloader] [handle_segments:1139] INFO: > Downloading Lecture Tracks...
Traceback (most recent call last):
  File "C:\Users\Ottoniel\Desktop\udemy-downloader-master\main.py", line 1940, in <module>
    main()
  File "C:\Users\Ottoniel\Desktop\udemy-downloader-master\main.py", line 1933, in main
    parse_new(_udemy)
  File "C:\Users\Ottoniel\Desktop\udemy-downloader-master\main.py", line 1469, in parse_new
    process_lecture(lecture, lecture_path,
  File "C:\Users\Ottoniel\Desktop\udemy-downloader-master\main.py", line 1348, in process_lecture
    handle_segments(source.get("download_url"),
  File "C:\Users\Ottoniel\Desktop\udemy-downloader-master\main.py", line 1151, in handle_segments
    log_subprocess_output("YTDLP-STDOUT", process.stdout)
  File "C:\Users\Ottoniel\Desktop\udemy-downloader-master\main.py", line 57, in log_subprocess_output
    logger.debug('[%s]: %r', prefix, line.decode("utf8").strip())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 28: invalid start byte

### Expected Result

Download a course

### Branch

master/main

### What operating systems are you seeing the problem on?

Windows

### Relevant log output

```shell
C:\Users\Ottoniel\Desktop\udemy-downloader-master>main.py -c https://www.udemy.com/course/javascript-fernando-herrera/ --download-assets -q 1080
[01:02:22] [udemy-downloader] [pre_run:276] WARNING: No cookies.txt file was found, you won't be able to download subscription courses! You can ignore ignore this if you don't plan to download a course included in a subscription plan.
[01:02:22] [udemy-downloader] [__init__:295] INFO: Login Success
[01:02:22] [udemy-downloader] [main:1660] INFO: > Fetching course information, this may take a minute...
[01:02:23] [udemy-downloader] [main:1663] INFO: > Course information retrieved!
[01:02:23] [udemy-downloader] [main:1669] INFO: > Fetching course content, this may take a minute...
[01:02:28] [udemy-downloader] [main:1686] INFO: > Course content retrieved!
[01:02:28] [udemy-downloader] [main:1712] INFO: > Processing course data, this may take a minute.
[01:02:28] [udemy-downloader] [main:1752] INFO: Processing 1 of 166
[01:02:28] [udemy-downloader] [main:1752] INFO: Processing 2 of 166
[01:02:28] [udemy-downloader] [main:1752] INFO: Processing 3 of 166
[01:02:29] [udemy-downloader] [main:1752] INFO: Processing 4 of 166
[01:02:30] [udemy-downloader] [main:1752] INFO: Processing 6 of 166
[01:02:31] [udemy-downloader] [main:1752] INFO: Processing 7 of 166
[01:02:31] [udemy-downloader] [main:1752] INFO: Processing 8 of 166
[01:02:31] [udemy-downloader] [main:1752] INFO: Processing 9 of 166
[01:02:32] [udemy-downloader] [main:1752] INFO: Processing 10 of 166
[01:02:33] [udemy-downloader] [main:1752] INFO: Processing 11 of 166
[01:02:35] [udemy-downloader] [main:1752] INFO: Processing 12 of 166
[01:02:35] [udemy-downloader] [main:1752] INFO: Processing 13 of 166
[01:02:36] [udemy-downloader] [main:1752] INFO: Processing 14 of 166
[01:02:37] [udemy-downloader] [main:1752] INFO: Processing 15 of 166
[01:02:37] [udemy-downloader] [main:1752] INFO: Processing 16 of 166
[01:02:38] [udemy-downloader] [main:1752] INFO: Processing 17 of 166
[01:02:38] [udemy-downloader] [main:1752] INFO: Processing 19 of 166
[01:02:39] [udemy-downloader] [main:1752] INFO: Processing 20 of 166
[01:02:39] [udemy-downloader] [main:1752] INFO: Processing 21 of 166
[01:02:40] [udemy-downloader] [main:1752] INFO: Processing 22 of 166
[01:02:41] [udemy-downloader] [main:1752] INFO: Processing 23 of 166
[01:02:42] [udemy-downloader] [main:1752] INFO: Processing 24 of 166
[01:02:43] [udemy-downloader] [main:1752] INFO: Processing 25 of 166
[01:02:44] [udemy-downloader] [main:1752] INFO: Processing 26 of 166
[01:02:44] [udemy-downloader] [main:1752] INFO: Processing 27 of 166
[01:02:45] [udemy-downloader] [main:1752] INFO: Processing 28 of 166
[01:02:46] [udemy-downloader] [main:1752] INFO: Processing 29 of 166
[01:02:48] [udemy-downloader] [main:1752] INFO: Processing 30 of 166
[01:02:48] [udemy-downloader] [main:1752] INFO: Processing 31 of 166
[01:02:48] [udemy-downloader] [main:1752] INFO: Processing 33 of 166
[01:02:49] [udemy-downloader] [main:1752] INFO: Processing 34 of 166
[01:02:49] [udemy-downloader] [main:1752] INFO: Processing 35 of 166
[01:02:50] [udemy-downloader] [main:1752] INFO: Processing 36 of 166
[01:02:51] [udemy-downloader] [main:1752] INFO: Processing 37 of 166
[01:02:53] [udemy-downloader] [main:1752] INFO: Processing 38 of 166
[01:02:54] [udemy-downloader] [main:1752] INFO: Processing 39 of 166
[01:02:57] [udemy-downloader] [main:1752] INFO: Processing 40 of 166
[01:02:58] [udemy-downloader] [main:1752] INFO: Processing 41 of 166
[01:02:58] [udemy-downloader] [main:1752] INFO: Processing 42 of 166
[01:02:59] [udemy-downloader] [main:1752] INFO: Processing 43 of 166
[01:03:00] [udemy-downloader] [main:1752] INFO: Processing 44 of 166
[01:03:01] [udemy-downloader] [main:1752] INFO: Processing 45 of 166
[01:03:01] [udemy-downloader] [main:1752] INFO: Processing 47 of 166
[01:03:02] [udemy-downloader] [main:1752] INFO: Processing 48 of 166
[01:03:02] [udemy-downloader] [main:1752] INFO: Processing 49 of 166
[01:03:02] [udemy-downloader] [main:1752] INFO: Processing 50 of 166
[01:03:03] [udemy-downloader] [main:1752] INFO: Processing 51 of 166
[01:03:03] [udemy-downloader] [main:1752] INFO: Processing 52 of 166
[01:03:04] [udemy-downloader] [main:1752] INFO: Processing 53 of 166
[01:03:05] [udemy-downloader] [main:1752] INFO: Processing 54 of 166
[01:03:06] [udemy-downloader] [main:1752] INFO: Processing 55 of 166
[01:03:07] [udemy-downloader] [main:1752] INFO: Processing 56 of 166
[01:03:08] [udemy-downloader] [main:1752] INFO: Processing 57 of 166
[01:03:09] [udemy-downloader] [main:1752] INFO: Processing 58 of 166
[01:03:10] [udemy-downloader] [main:1752] INFO: Processing 59 of 166
[01:03:11] [udemy-downloader] [main:1752] INFO: Processing 60 of 166
[01:03:13] [udemy-downloader] [main:1752] INFO: Processing 61 of 166
[01:03:14] [udemy-downloader] [main:1752] INFO: Processing 62 of 166
[01:03:14] [udemy-downloader] [main:1752] INFO: Processing 64 of 166
[01:03:14] [udemy-downloader] [main:1752] INFO: Processing 65 of 166
[01:03:14] [udemy-downloader] [main:1752] INFO: Processing 66 of 166
[01:03:15] [udemy-downloader] [main:1752] INFO: Processing 67 of 166
[01:03:15] [udemy-downloader] [main:1752] INFO: Processing 68 of 166
[01:03:16] [udemy-downloader] [main:1752] INFO: Processing 69 of 166
[01:03:17] [udemy-downloader] [main:1752] INFO: Processing 70 of 166
[01:03:18] [udemy-downloader] [main:1752] INFO: Processing 71 of 166
[01:03:19] [udemy-downloader] [main:1752] INFO: Processing 72 of 166
[01:03:19] [udemy-downloader] [main:1752] INFO: Processing 73 of 166
[01:03:20] [udemy-downloader] [main:1752] INFO: Processing 75 of 166
[01:03:20] [udemy-downloader] [main:1752] INFO: Processing 76 of 166
[01:03:20] [udemy-downloader] [main:1752] INFO: Processing 77 of 166
[01:03:21] [udemy-downloader] [main:1752] INFO: Processing 78 of 166
[01:03:22] [udemy-downloader] [main:1752] INFO: Processing 79 of 166
[01:03:22] [udemy-downloader] [main:1752] INFO: Processing 80 of 166
[01:03:23] [udemy-downloader] [main:1752] INFO: Processing 81 of 166
[01:03:24] [udemy-downloader] [main:1752] INFO: Processing 82 of 166
[01:03:25] [udemy-downloader] [main:1752] INFO: Processing 83 of 166
[01:03:26] [udemy-downloader] [main:1752] INFO: Processing 84 of 166
[01:03:27] [udemy-downloader] [main:1752] INFO: Processing 85 of 166
[01:03:28] [udemy-downloader] [main:1752] INFO: Processing 86 of 166
[01:03:28] [udemy-downloader] [main:1752] INFO: Processing 88 of 166
[01:03:28] [udemy-downloader] [main:1752] INFO: Processing 89 of 166
[01:03:28] [udemy-downloader] [main:1752] INFO: Processing 90 of 166
[01:03:29] [udemy-downloader] [main:1752] INFO: Processing 91 of 166
[01:03:30] [udemy-downloader] [main:1752] INFO: Processing 92 of 166
[01:03:32] [udemy-downloader] [main:1752] INFO: Processing 93 of 166
[01:03:34] [udemy-downloader] [main:1752] INFO: Processing 94 of 166
[01:03:34] [udemy-downloader] [main:1752] INFO: Processing 95 of 166
[01:03:35] [udemy-downloader] [main:1752] INFO: Processing 96 of 166
[01:03:36] [udemy-downloader] [main:1752] INFO: Processing 97 of 166
[01:03:37] [udemy-downloader] [main:1752] INFO: Processing 98 of 166
[01:03:38] [udemy-downloader] [main:1752] INFO: Processing 99 of 166
[01:03:40] [udemy-downloader] [main:1752] INFO: Processing 100 of 166
[01:03:41] [udemy-downloader] [main:1752] INFO: Processing 101 of 166
[01:03:42] [udemy-downloader] [main:1752] INFO: Processing 102 of 166
[01:03:43] [udemy-downloader] [main:1752] INFO: Processing 103 of 166
[01:03:43] [udemy-downloader] [main:1752] INFO: Processing 105 of 166
[01:03:44] [udemy-downloader] [main:1752] INFO: Processing 106 of 166
[01:03:44] [udemy-downloader] [main:1752] INFO: Processing 107 of 166
[01:03:45] [udemy-downloader] [main:1752] INFO: Processing 108 of 166
[01:03:45] [udemy-downloader] [main:1752] INFO: Processing 109 of 166
[01:03:46] [udemy-downloader] [main:1752] INFO: Processing 110 of 166
[01:03:47] [udemy-downloader] [main:1752] INFO: Processing 112 of 166
[01:03:48] [udemy-downloader] [main:1752] INFO: Processing 113 of 166
[01:03:48] [udemy-downloader] [main:1752] INFO: Processing 114 of 166
[01:03:49] [udemy-downloader] [main:1752] INFO: Processing 115 of 166
[01:03:49] [udemy-downloader] [main:1752] INFO: Processing 116 of 166
[01:03:50] [udemy-downloader] [main:1752] INFO: Processing 117 of 166
[01:03:51] [udemy-downloader] [main:1752] INFO: Processing 118 of 166
[01:03:52] [udemy-downloader] [main:1752] INFO: Processing 119 of 166
[01:03:53] [udemy-downloader] [main:1752] INFO: Processing 120 of 166
[01:03:54] [udemy-downloader] [main:1752] INFO: Processing 121 of 166
[01:03:55] [udemy-downloader] [main:1752] INFO: Processing 122 of 166
[01:03:56] [udemy-downloader] [main:1752] INFO: Processing 123 of 166
[01:03:56] [udemy-downloader] [main:1752] INFO: Processing 124 of 166
[01:03:57] [udemy-downloader] [main:1752] INFO: Processing 125 of 166
[01:03:58] [udemy-downloader] [main:1752] INFO: Processing 126 of 166
[01:03:59] [udemy-downloader] [main:1752] INFO: Processing 127 of 166
[01:04:00] [udemy-downloader] [main:1752] INFO: Processing 128 of 166
[01:04:00] [udemy-downloader] [main:1752] INFO: Processing 130 of 166
[01:04:01] [udemy-downloader] [main:1752] INFO: Processing 131 of 166
[01:04:01] [udemy-downloader] [main:1752] INFO: Processing 132 of 166
[01:04:02] [udemy-downloader] [main:1752] INFO: Processing 133 of 166
[01:04:02] [udemy-downloader] [main:1752] INFO: Processing 134 of 166
[01:04:03] [udemy-downloader] [main:1752] INFO: Processing 135 of 166
[01:04:03] [udemy-downloader] [main:1752] INFO: Processing 136 of 166
[01:04:05] [udemy-downloader] [main:1752] INFO: Processing 137 of 166
[01:04:05] [udemy-downloader] [main:1752] INFO: Processing 138 of 166
[01:04:06] [udemy-downloader] [main:1752] INFO: Processing 139 of 166
[01:04:07] [udemy-downloader] [main:1752] INFO: Processing 140 of 166
[01:04:08] [udemy-downloader] [main:1752] INFO: Processing 141 of 166
[01:04:09] [udemy-downloader] [main:1752] INFO: Processing 142 of 166
[01:04:10] [udemy-downloader] [main:1752] INFO: Processing 143 of 166
[01:04:11] [udemy-downloader] [main:1752] INFO: Processing 144 of 166
[01:04:12] [udemy-downloader] [main:1752] INFO: Processing 145 of 166
[01:04:12] [udemy-downloader] [main:1752] INFO: Processing 147 of 166
[01:04:13] [udemy-downloader] [main:1752] INFO: Processing 148 of 166
[01:04:13] [udemy-downloader] [main:1752] INFO: Processing 149 of 166
[01:04:13] [udemy-downloader] [main:1752] INFO: Processing 150 of 166
[01:04:14] [udemy-downloader] [main:1752] INFO: Processing 151 of 166
[01:04:15] [udemy-downloader] [main:1752] INFO: Processing 152 of 166
[01:04:16] [udemy-downloader] [main:1752] INFO: Processing 153 of 166
[01:04:17] [udemy-downloader] [main:1752] INFO: Processing 154 of 166
[01:04:18] [udemy-downloader] [main:1752] INFO: Processing 155 of 166
[01:04:19] [udemy-downloader] [main:1752] INFO: Processing 156 of 166
[01:04:20] [udemy-downloader] [main:1752] INFO: Processing 157 of 166
[01:04:20] [udemy-downloader] [main:1752] INFO: Processing 158 of 166
[01:04:21] [udemy-downloader] [main:1752] INFO: Processing 159 of 166
[01:04:22] [udemy-downloader] [main:1752] INFO: Processing 160 of 166
[01:04:23] [udemy-downloader] [main:1752] INFO: Processing 161 of 166
[01:04:24] [udemy-downloader] [main:1752] INFO: Processing 162 of 166
[01:04:25] [udemy-downloader] [main:1752] INFO: Processing 163 of 166
[01:04:25] [udemy-downloader] [main:1752] INFO: Processing 165 of 166
[01:04:26] [udemy-downloader] [parse_new:1411] INFO: Chapter(s) (13)
[01:04:26] [udemy-downloader] [parse_new:1412] INFO: Lecture(s) (153)
[01:04:26] [udemy-downloader] [parse_new:1426] INFO: ======= Processing chapter 1 of 13 =======
[01:04:26] [udemy-downloader] [parse_new:1444] INFO:   > Processing lecture 1 of 153
[01:04:26] [udemy-downloader] [parse_new:1449] INFO:       > Lecture '001 Introducción' is already downloaded, skipping...
[01:04:26] [udemy-downloader] [parse_new:1485] INFO:     > Processing 0 asset(s) for lecture...
[01:04:26] [udemy-downloader] [parse_new:1444] INFO:   > Processing lecture 2 of 153
[01:04:26] [udemy-downloader] [parse_new:1449] INFO:       > Lecture '002 ¿Cómo funcionará el curso' is already downloaded, skipping...
[01:04:26] [udemy-downloader] [parse_new:1485] INFO:     > Processing 0 asset(s) for lecture...
[01:04:26] [udemy-downloader] [parse_new:1444] INFO:   > Processing lecture 3 of 153
[01:04:26] [udemy-downloader] [process_lecture:1346] INFO:       > Lecture '003 ¿Cómo realizar preguntas' has DRM, attempting to download
[01:04:26] [udemy-downloader] [handle_segments:1139] INFO: > Downloading Lecture Tracks...
Traceback (most recent call last):
  File "C:\Users\Ottoniel\Desktop\udemy-downloader-master\main.py", line 1940, in <module>
    main()
  File "C:\Users\Ottoniel\Desktop\udemy-downloader-master\main.py", line 1933, in main
    parse_new(_udemy)
  File "C:\Users\Ottoniel\Desktop\udemy-downloader-master\main.py", line 1469, in parse_new
    process_lecture(lecture, lecture_path,
  File "C:\Users\Ottoniel\Desktop\udemy-downloader-master\main.py", line 1348, in process_lecture
    handle_segments(source.get("download_url"),
  File "C:\Users\Ottoniel\Desktop\udemy-downloader-master\main.py", line 1151, in handle_segments
    log_subprocess_output("YTDLP-STDOUT", process.stdout)
  File "C:\Users\Ottoniel\Desktop\udemy-downloader-master\main.py", line 57, in log_subprocess_output
    logger.debug('[%s]: %r', prefix, line.decode("utf8").strip())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 28: invalid start byte
```

**Comment by superman2197** [comment]
@eliottp1089 How are getting the Keys? I have tried multiple things including replacing DLLs, using older versions of chrome, but the widewine decryptor is not working anymore.
