### ISSUE TITLE
[Bug]: error on feat-mkv branch

### ISSUE THREAD

**Issue by Ex-Communicad0** [Puyodead1/udemy-downloader#109]
### What happened?

Looks like the error is something in script can you update this

### Expected Result

Run feat-mkv version properly thats it

### Branch

Other (Enter below)

### What operating systems are you seeing the problem on?

Windows, Linux/Unix

### Relevant log output

```shell
Traceback (most recent call last):
  File "main.py", line 1438, in <module>
    version='You are running version {version}'.format(version=get_version_string()))
  File "main.py", line 1337, in get_version_string
    repo = git.Repo(search_parent_directories=True)
  File "/usr/local/lib/python3.7/dist-packages/git/repo/base.py", line 224, in __init__
    self.working_dir: Optional[PathLike] = self._working_tree_dir or self.common_dir
  File "/usr/local/lib/python3.7/dist-packages/git/repo/base.py", line 307, in common_dir
    raise InvalidGitRepositoryError()
git.exc.InvalidGitRepositoryError
```

**Comment by Puyodead1** [comment]
that branch is extremely outdated and has been abandoned.
