### ISSUE TITLE
[Bug]: Decryption returned a non-zero exit code

### ISSUE THREAD

**Issue by Ex-Communicad0** [Puyodead1/udemy-downloader#116]
### What happened?

Decryption error

### Expected Result

decrypt should work properly

### Branch

master/main

### What operating systems are you seeing the problem on?

Linux/Unix

### Relevant log output

```shell
[05:55:04] [udemy-downloader] [handle_segments:1157] INFO: > Lecture Tracks Downloaded
[05:55:04] [udemy-downloader] [handle_segments:1166] INFO: KID for video file is: 84989ADEF469484FB1336529353E11C8
[05:55:04] [udemy-downloader] [handle_segments:1173] INFO: KID for audio file is: 84989ADEF469484FB1336529353E11C8
[05:55:04] [udemy-downloader] [handle_segments:1179] INFO: > Decrypting video, this might take a minute...
ERROR: unknown command line flag 'enable_raw_key_decryption'
ERROR: unknown command line flag 'keys'
[05:55:05] [udemy-downloader] [handle_segments:1206] ERROR: Error: 
Traceback (most recent call last):
  File "main.py", line 1180, in handle_segments
    ret_code = decrypt(video_kid, video_filepath_enc, video_filepath_dec)
  File "main.py", line 1123, in decrypt
    raise Exception("Decryption returned a non-zero exit code")
Exception: Decryption returned a non-zero exit code
```

**Comment by Ex-Communicad0** [comment]
feat-selenium branch also throwing same error

**Comment by Puyodead1** [comment]
what version of shaka-packager are you using?

**Comment by Ex-Communicad0** [comment]
1.1.8

**Comment by Puyodead1** [comment]
> 1.1.8 or latest
> 
> Shaka-packager (main repo) & mp4decrypt (selenium version) both having same issue on ubuntu

that's extremely old.... the latest version is 2.6.1
