### ISSUE TITLE
[Bug]: main.py giving errors even after installing all dependencies

### ISSUE THREAD

**Issue by 4nur4g** [Puyodead1/udemy-downloader#120]
### What happened?

Even after installing the required modules, main.py keeps on giving errors. I tried the script with Python 3.8 as well, still, the problem persists.
![cmd_Tl5fWBMRlP](https://user-images.githubusercontent.com/33851499/174975185-c306e41b-279e-4721-8a73-f34ae8fabcce.png)
 

### Expected Result

main.py should have opened normally. python main.py -h should have provided me with potential options. 

### Branch

master/main

### What operating systems are you seeing the problem on?

Windows

### Relevant log output

```shell
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    from utils import extract_kid
  File "C:\Users\anura\OneDrive\Desktop\Udemy\Downloader 2\udemy-downloader-master\utils.py", line 3, in <module>
    import widevine_pssh_pb2
  File "C:\Users\anura\OneDrive\Desktop\Udemy\Downloader 2\udemy-downloader-master\widevine_pssh_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "C:\Users\anura\anaconda3\envs\py8\lib\site-packages\google\protobuf\descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by Puyodead1** [comment]
#118
