### ISSUE TITLE
[Bug]: unable to start download

### ISSUE THREAD

**Issue by CHITTIMOTU** [Puyodead1/udemy-downloader#121]
### What happened?

PIP command not working
![image](https://user-images.githubusercontent.com/65209890/177388569-9ce41acc-b3f3-493e-8226-cd4ed8490a9b.png)

### Expected Result

course will start download

### Branch

master/main

### What operating systems are you seeing the problem on?

Windows

### Relevant log output

```shell
Microsoft Windows [Version 10.0.19044.1586]
(c) Microsoft Corporation. All rights reserved.

D:\Udemy\udl>python main.py -c https://www.udemy.com/course/microsoft-azure-beginners-guide/learn/lecture/16291138
Traceback (most recent call last):
  File "D:\Udemy\udl\main.py", line 1941, in <module>
    pre_run()
  File "D:\Udemy\udl\main.py", line 269, in pre_run
    keys = json.loads(keyfile.read())
  File "C:\Users\Naveen\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Naveen\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Naveen\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 3 column 1 (char 72)

D:\Udemy\udl>
```

**Comment by Puyodead1** [comment]
keyfile.json contains invalid JSON. not a bug
