### ISSUE TITLE
[Bug]: Failed request url, 403 Forbidden

### ISSUE THREAD

**Issue by huytemp01** [Puyodead1/udemy-downloader#122]
### What happened?

![Capture](https://user-images.githubusercontent.com/32239830/177903670-828f7114-f92b-4ea1-a3c6-f8f60d8eda83.PNG)

### Expected Result

course will start download

### Branch

master/main

### What operating systems are you seeing the problem on?

Linux/Unix

### Relevant log output

```shell
[02:13:55] [udemy-downloader] [__init__:296] INFO: Login Success
[02:13:55] [udemy-downloader] [main:1644] INFO: > Fetching course information, this may take a minute...
[02:13:55] [udemy-downloader] [_get:892] ERROR: Failed request https://www.udemy.com/course/grpc-nodejs/learn/
[02:13:55] [udemy-downloader] [_get:894] ERROR: 403 Forbidden, retrying (attempt 0 )...
[02:13:56] [udemy-downloader] [_get:892] ERROR: Failed request https://www.udemy.com/course/grpc-nodejs/learn/
[02:13:56] [udemy-downloader] [_get:894] ERROR: 403 Forbidden, retrying (attempt 1 )...
[02:13:57] [udemy-downloader] [_get:892] ERROR: Failed request https://www.udemy.com/course/grpc-nodejs/learn/
[02:13:57] [udemy-downloader] [_get:894] ERROR: 403 Forbidden, retrying (attempt 2 )...
[02:13:58] [udemy-downloader] [_get:892] ERROR: Failed request https://www.udemy.com/course/grpc-nodejs/learn/
[02:13:58] [udemy-downloader] [_get:894] ERROR: 403 Forbidden, retrying (attempt 3 )...
[02:13:59] [udemy-downloader] [_get:892] ERROR: Failed request https://www.udemy.com/course/grpc-nodejs/learn/
[02:13:59] [udemy-downloader] [_get:894] ERROR: 403 Forbidden, retrying (attempt 4 )...
[02:14:00] [udemy-downloader] [_get:892] ERROR: Failed request https://www.udemy.com/course/grpc-nodejs/learn/
[02:14:00] [udemy-downloader] [_get:894] ERROR: 403 Forbidden, retrying (attempt 5 )...
[02:14:01] [udemy-downloader] [_get:892] ERROR: Failed request https://www.udemy.com/course/grpc-nodejs/learn/
[02:14:01] [udemy-downloader] [_get:894] ERROR: 403 Forbidden, retrying (attempt 6 )...
[02:14:02] [udemy-downloader] [_get:892] ERROR: Failed request https://www.udemy.com/course/grpc-nodejs/learn/
[02:14:02] [udemy-downloader] [_get:894] ERROR: 403 Forbidden, retrying (attempt 7 )...
[02:14:03] [udemy-downloader] [_get:892] ERROR: Failed request https://www.udemy.com/course/grpc-nodejs/learn/
[02:14:03] [udemy-downloader] [_get:894] ERROR: 403 Forbidden, retrying (attempt 8 )...
[02:14:04] [udemy-downloader] [_get:892] ERROR: Failed request https://www.udemy.com/course/grpc-nodejs/learn/
[02:14:04] [udemy-downloader] [_get:894] ERROR: 403 Forbidden, retrying (attempt 9 )...
Traceback (most recent call last):
  File "main.py", line 1924, in <module>
    main()
  File "main.py", line 1646, in main
    course_id, course_info = udemy._extract_course_info(course_url)
  File "main.py", line 855, in _extract_course_info
    url)
  File "main.py", line 815, in _extract_subscription_course_info
    course_html = self.session._get(url).text
AttributeError: 'NoneType' object has no attribute 'text'
```

### Other information
Udemy Personal Plan

**Comment by Puyodead1** [comment]
you have to use the selenium branch with -sc option.
