### ISSUE TITLE
[Bug]: Udemy Pro/Personal plans bug

### ISSUE THREAD

**Issue by lls275** [Puyodead1/udemy-downloader#123]
### What happened?

```
[07:33:40] [udemy-downloader] [main:1971] INFO: > Fetching course information, this may take a minute...
[07:33:40] [udemy-downloader] [main:1974] INFO: Extracting course information as a subscription course...
[07:34:41] [udemy-downloader] [_extract_course_info_sub:1119] ERROR: PDF math rendering timed out
Traceback (most recent call last):
  File "/Users/wt/Desktop/feat-selenium/main.py", line 1115, in _extract_course_info_sub
    WebDriverWait(selenium.driver, 60).until(EC.title_is(
  File "/Users/wt/Desktop/feat-selenium/venv/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/wt/Desktop/feat-selenium/main.py", line 2266, in <module>
    main()
  File "/Users/wt/Desktop/feat-selenium/main.py", line 1976, in main
    course_id, course_info = udemy._extract_course_info_sub(
  File "/Users/wt/Desktop/feat-selenium/main.py", line 1120, in _extract_course_info_sub
    self.log = self.get_log(selenium.driver) + '\nPDF math rendering timed out'
AttributeError: 'Udemy' object has no attribute 'get_log'
python-BaseException
```

### Expected Result

```
[07:33:40] [udemy-downloader] [main:1971] INFO: > Fetching course information, this may take a minute...
[07:33:40] [udemy-downloader] [main:1974] INFO: Extracting course information as a subscription course...
[07:34:41] [udemy-downloader] [_extract_course_info_sub:1119] ERROR: PDF math rendering timed out
Traceback (most recent call last):
  File "/Users/wt/Desktop/feat-selenium/main.py", line 1115, in _extract_course_info_sub
    WebDriverWait(selenium.driver, 60).until(EC.title_is(
  File "/Users/wt/Desktop/feat-selenium/venv/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/wt/Desktop/feat-selenium/main.py", line 2266, in <module>
    main()
  File "/Users/wt/Desktop/feat-selenium/main.py", line 1976, in main
    course_id, course_info = udemy._extract_course_info_sub(
  File "/Users/wt/Desktop/feat-selenium/main.py", line 1120, in _extract_course_info_sub
    self.log = self.get_log(selenium.driver) + '\nPDF math rendering timed out'
AttributeError: 'Udemy' object has no attribute 'get_log'
python-BaseException
```

### Branch

feat-selenium

### What operating systems are you seeing the problem on?

Windows, Other (Enter Below)

**Comment by Puyodead1** [comment]
update chrome, remove selenium_data folder and try again.
