### ISSUE TITLE
[Bug]: Can't download course without DRM

### ISSUE THREAD

**Issue by Zeddex** [Puyodead1/udemy-downloader#127]
### What happened?

I'm trying to download a course without DRM protection, but get an error.

### Expected Result

Download course

### Branch

master/main

### Relevant log output

```shell
[03:28:10] [udemy-downloader] [parse_new:1293] INFO:   > Processing lecture 224 of 224
[03:28:10] [udemy-downloader] [process_lecture:1231] INFO:       > Lecture doesn't have DRM, attempting to download...
[03:28:10] [udemy-downloader] [process_lecture:1236] INFO:       ====== Selected quality: hls 1080
[03:28:10] [udemy-downloader] [process_lecture:1256] ERROR: >        Error downloading lecture
Traceback (most recent call last):
  File "D:\...\udemy-downloader\main.py", line 1245, in process_lecture
    process = subprocess.Popen(args)
  File "C:\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by Zeddex** [comment]
The same situation with the DRM protected course (I have keys). At the end I get errors:
`
[05:22:17] [udemy-downloader] [handle_segments:1034] INFO: > Downloading Lecture Tracks...
Traceback (most recent call last):
  File "D:\...\udemy-downloader\main.py", line 1696, in <module>
    main()
  File "D:\...\udemy-downloader\main.py", line 1689, in main
    parse_new(_udemy)
  File "D:\...\udemy-downloader\main.py", line 1312, in parse_new
    process_lecture(lecture, lecture_path, lecture_file_name, chapter_dir)
  File "D:\...\udemy-downloader\main.py", line 1222, in process_lecture
    handle_segments(source.get("download_url"), source.get("format_id"), lecture_title, lecture_path, lecture_file_name, chapter_dir)
  File "D:\...\udemy-downloader\main.py", line 1055, in handle_segments
    process = subprocess.Popen(args)
  File "C:\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
`

**Comment by Puyodead1** [comment]
You didn't install ytdlp

**Comment by Zeddex** [comment]
Thaks, it works
