### ISSUE TITLE
[Bug]: Selenium Crash

### ISSUE THREAD

**Issue by YspCoder** [Puyodead1/udemy-downloader#139]
### What happened?

Traceback (most recent call last):
  File "main.py", line 1991, in <module>
    main()
  File "main.py", line 1754, in main
    course_id, course_info = udemy._extract_course_info_sub(selenium, course_url)
  File "main.py", line 1030, in _extract_course_info_sub
    self._selenium_login(selenium.driver)
  File "main.py", line 988, in _selenium_login
    WebDriverWait(driver, 60).until(EC.visibility_of_element_located((By.ID, "id_email")))
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/support/wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

### Expected Result

download ...

### Branch

feat-selenium

### What operating systems are you seeing the problem on?

Linux/Unix

**Comment by Puyodead1** [comment]
most likely a captcha is preventing the program from continuing. I would suggest trying the feat/cookies branch.
