### ISSUE TITLE
[Bug]: Suddenly Stops without reason and without errors, simply is stucked

### ISSUE THREAD

**Issue by hstanleycrow** [Puyodead1/udemy-downloader#146]
### What happened?

I am trying to download a very large course with DRM, it starts very well, but suddenly and without any reason the scripts stops in something like this: "[download]  97.9% of ~  25.64MiB at    2.81MiB/s ETA 00:00 (frag 103/108)", 
or "[download]  86.4% of ~   5.21MiB at    2.38MiB/s ETA 00:00 (frag 94/108)"
so, I wait and wait and wait and nothing happen, so I use Ctrl + C to cancel de script and start over again.
After that, the scripts start to download again, and after a minutos, stops again.
I am not sure what is the problem or how to debug it, may be you can help me.

I read this " If you experience any issues while using this option, DO NOT open a bug report" but i don't know what can I do, may be this is not a bug, but i want any clue. Thank you and I apologies if this report is a problem.

On the logs i can see a keyerror for decryption, and I think i have the right keys, is there a way to know if i have the right key and key ID?

PD: the downloaded encripted files before the script stops has 2 files one with m4a extesion and another one with .mp4 extension but the files doesn't works, I mean, I can't watch 'em, and I am not sure if this is a normal behavior and I need to do something, or this is a final task of the script and because it stops, It doesn't do it?

Sorry for my doubts

### Expected Result

Download all the files

### Branch

master/main

### What operating systems are you seeing the problem on?

Windows

### Relevant log output

```shell
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\UDL\udemy-downloader\main.py", line 1085, in handle_segments
    ret_code = decrypt(video_kid, video_filepath_enc, video_filepath_dec)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\UDL\udemy-downloader\main.py", line 1006, in decrypt
    raise KeyError("Key not found")
KeyError: 'Key not found'
[09:12:29] [udemy-downloader] [parse_new:1329] INFO:     > Processing 0 asset(s) for lecture...
[09:12:29] [udemy-downloader] [parse_new:1284] INFO: ======= Processing chapter 2 of 93 =======
[09:12:29] [udemy-downloader] [parse_new:1297] INFO:   > Processing lecture 8 of 747
[09:12:29] [udemy-downloader] [process_lecture:1225] INFO:       > Lecture '001 Introducción a las variables' has DRM, attempting to download
[09:12:29] [udemy-downloader] [handle_segments:1038] INFO: > Downloading Lecture Tracks...
[09:12:30] [udemy-downloader] [handle_segments:1063] INFO: > Lecture Tracks Downloaded
[09:12:30] [udemy-downloader] [handle_segments:1071] INFO: KID for video file is: 4C51F598DAA5434DBB91110F16D8C6DF
[09:12:30] [udemy-downloader] [handle_segments:1078] INFO: KID for audio file is: 4C51F598DAA5434DBB91110F16D8C6DF
[09:12:30] [udemy-downloader] [handle_segments:1084] INFO: > Decrypting video, this might take a minute...
[09:12:30] [udemy-downloader] [handle_segments:1107] ERROR: Error: 
Traceback (most recent call last):
  File "D:\python\UDL\udemy-downloader\main.py", line 1004, in decrypt
    key = keys[kid.lower()]
          ~~~~^^^^^^^^^^^^^
KeyError: '4c51f598daa5434dbb91110f16d8c6df'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\UDL\udemy-downloader\main.py", line 1085, in handle_segments
    ret_code = decrypt(video_kid, video_filepath_enc, video_filepath_dec)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\UDL\udemy-downloader\main.py", line 1006, in decrypt
    raise KeyError("Key not found")
KeyError: 'Key not found'
[09:12:30] [udemy-downloader] [parse_new:1329] INFO:     > Processing 1 asset(s) for lecture...
[09:12:30] [udemy-downloader] [parse_new:1297] INFO:   > Processing lecture 9 of 747
[09:12:30] [udemy-downloader] [process_lecture:1225] INFO:       > Lecture '002 Ejemplos de variables' has DRM, attempting to download
[09:12:30] [udemy-downloader] [handle_segments:1038] INFO: > Downloading Lecture Tracks...
```

**Comment by Ex-Communicad0** [comment]
same issue for Linux

**Comment by Puyodead1** [comment]
> same issue for Linux
> 
> i think some issue with the yt-dlp downloader or aria2c downloader
> 
> it stuck in the middle, downloads all frags but don't merge them on videos, its stuck there forever

aria2c hasn't had an update in like 2 years, so its not that. its most likely yt-dlp. This isn't an issue with the script directly.

**Comment by bob312123** [comment]
Do you know which version of the Python package `yt_dlp` works for this?
