### ISSUE TITLE
[Bug]:  403 Forbidden  from cookie file

### ISSUE THREAD

**Issue by mahnotz** [Puyodead1/udemy-downloader#147]
### What happened?

hi
i want to use cookie file
I have subs plan udemy
but I get this error 403 Forbidden

### Expected Result

download course

### Branch

master/main

### What operating systems are you seeing the problem on?

Windows

### Relevant log output

```shell
[11:31:54] [udemy-downloader] [__init__:296] INFO: Login Success
[11:31:54] [udemy-downloader] [main:1663] INFO: > Fetching course information, this may take a minute...
[11:31:58] [udemy-downloader] [_get:892] ERROR: Failed request https://www.udemy.com/course/the-complete-sql-bootcamp/learn
[11:31:59] [udemy-downloader] [_get:893] ERROR: 403 Forbidden, retrying (attempt 0 )...
[11:32:01] [udemy-downloader] [_get:892] ERROR: Failed request https://www.udemy.com/course/the-complete-sql-bootcamp/learn
[11:32:01] [udemy-downloader] [_get:893] ERROR: 403 Forbidden, retrying (attempt 1 )...
[11:32:04] [udemy-downloader] [_get:892] ERROR: Failed request https://www.udemy.com/course/the-complete-sql-bootcamp/learn
[11:32:04] [udemy-downloader] [_get:893] ERROR: 403 Forbidden, retrying (attempt 2 )...
[11:32:07] [udemy-downloader] [_get:892] ERROR: Failed request https://www.udemy.com/course/the-complete-sql-bootcamp/learn
[11:32:07] [udemy-downloader] [_get:893] ERROR: 403 Forbidden, retrying (attempt 3 )...
[11:32:10] [udemy-downloader] [_get:892] ERROR: Failed request https://www.udemy.com/course/the-complete-sql-bootcamp/learn
[11:32:10] [udemy-downloader] [_get:893] ERROR: 403 Forbidden, retrying (attempt 4 )...
[11:32:13] [udemy-downloader] [_get:892] ERROR: Failed request https://www.udemy.com/course/the-complete-sql-bootcamp/learn
[11:32:13] [udemy-downloader] [_get:893] ERROR: 403 Forbidden, retrying (attempt 5 )...
[11:32:16] [udemy-downloader] [_get:892] ERROR: Failed request https://www.udemy.com/course/the-complete-sql-bootcamp/learn
[11:32:16] [udemy-downloader] [_get:893] ERROR: 403 Forbidden, retrying (attempt 6 )...
[11:32:19] [udemy-downloader] [_get:892] ERROR: Failed request https://www.udemy.com/course/the-complete-sql-bootcamp/learn
[11:32:19] [udemy-downloader] [_get:893] ERROR: 403 Forbidden, retrying (attempt 7 )...
[11:32:21] [udemy-downloader] [_get:892] ERROR: Failed request https://www.udemy.com/course/the-complete-sql-bootcamp/learn
[11:32:21] [udemy-downloader] [_get:893] ERROR: 403 Forbidden, retrying (attempt 8 )...
[11:32:24] [udemy-downloader] [_get:892] ERROR: Failed request https://www.udemy.com/course/the-complete-sql-bootcamp/learn
[11:32:24] [udemy-downloader] [_get:893] ERROR: 403 Forbidden, retrying (attempt 9 )...
Traceback (most recent call last):
  File "\udemy-shel\main.py", line 1943, in <module>
    main()
  File "\udemy-shel\main.py", line 1665, in main
    course_id, course_info = udemy._extract_course_info(course_url)
  File "\udemy-shel\main.py", line 854, in _extract_course_info
    course_id, portal_name = self._extract_subscription_course_info(
  File "\udemy-shel\main.py", line 815, in _extract_subscription_course_info
    course_html = self.session._get(url).text
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by Puyodead1** [comment]
you cannot use the main branch for subscription plans. you have to use selenium

**Comment by mahnotz** [comment]
i used branch selenium but this error to 

CRITICAL: [-] Login Failure! You are probably missing an access token!

**Comment by Puyodead1** [comment]
> i used the selenium branch but this error too
> 
> CRITICAL: [-] Login Failure! You are probably missing an access token!

and? the message tells you the problem

**Comment by mahnotz** [comment]
i used of this 

https://github.com/Puyodead1/udemy-downloader#udemy-subscription-plans

but say not login

**Comment by Puyodead1** [comment]
> i used of this
> 
> https://github.com/Puyodead1/udemy-downloader#udemy-subscription-plans
> 
> but say not login

you might not be using the `-sc` option.

**Comment by mahnotz** [comment]
python  main.py -c https://www.udemy.com/course/adobe-photoshop-cc-essentials-training-course/learn --download-captions -l en -q 720 --download-assets -sc
[08:10:58] [udemy-downloader] [__init__:391] CRITICAL: [-] Login Failure! You are probably missing an access token!


i used with -sc and without -sc

**Comment by Puyodead1** [comment]
> python main.py -c https://www.udemy.com/course/adobe-photoshop-cc-essentials-training-course/learn --download-captions -l en -q 720 --download-assets -sc [08:10:58] [udemy-downloader] [**init**:391] CRITICAL: [-] Login Failure! You are probably missing an access token!
> 
> i used with -sc and without -sc

you still need to pass the bearer token

**Comment by mahnotz** [comment]
python  main.py -c https://www.udemy.com/course/adobe-photoshop-cc-essentials-training-course/learn --download-captions -l en -q 720 --download-assets -b xxxxx -sc
[12:20:45] [udemy-downloader] [__init__:389] INFO: [+] Login Success
[12:20:50] [udemy-downloader] [main:1750] INFO: > Fetching course information, this may take a minute...
[12:20:50] [udemy-downloader] [main:1753] INFO: Extracting course information as a subscription course...
Is Authenticated: False
[12:20:54] [udemy-downloader] [_extract_course_info_sub:1027] CRITICAL: Username or password not provided, cannot continue

**Comment by Puyodead1** [comment]
> python main.py -c https://www.udemy.com/course/adobe-photoshop-cc-essentials-training-course/learn --download-captions -l en -q 720 --download-assets -b xxxxx -sc [12:20:45] [udemy-downloader] [**init**:389] INFO: [+] Login Success [12:20:50] [udemy-downloader] [main:1750] INFO: > Fetching course information, this may take a minute... [12:20:50] [udemy-downloader] [main:1753] INFO: Extracting course information as a subscription course... Is Authenticated: False [12:20:54] [udemy-downloader] [_extract_course_info_sub:1027] CRITICAL: Username or password not provided, cannot continue

edit the config.toml

**Comment by mahnotz** [comment]
What should I edit?

i dont want set username and password

**Comment by Puyodead1** [comment]
> What should I edit?
> 
> i dont want set username and password

then you cant use the program.
