### ISSUE TITLE
[Bug]:  AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by TriRizki** [Puyodead1/udemy-downloader#157]
### What happened?

i am trying to get the course information from my udemy personal subscription. I  have setup the bearer token at .env file and cookies from console tab and put it at cookies.txt file on the same folder as main.py. I also have use the correct url `https://www.udemy.com/course/<course name>/learn/` in my case it's `https://www.udemy.com/course/master-data-engineering-using-gcp-data-analytics/learn/`.

I run this command
`python .\main.py -c https://www.udemy.com/course/master-data-engineering-using-gcp-data-analytics/learn/ --info -sc`

and get the following result
```
[02:17:52] [udemy-downloader] [__init__:331] INFO: Login Success
[02:17:52] [udemy-downloader] [main:1629] INFO: > Fetching course information, this may take a minute...
[02:17:54] [udemy-downloader] [_get:874] ERROR: Failed request https://www.udemy.com/course/master-data-engineering-using-gcp-data-analytics/learn/
[02:17:54] [udemy-downloader] [_get:875] ERROR: 403 Forbidden, retrying (attempt 0 )...
[02:17:56] [udemy-downloader] [_get:874] ERROR: Failed request https://www.udemy.com/course/master-data-engineering-using-gcp-data-analytics/learn/
[02:17:56] [udemy-downloader] [_get:875] ERROR: 403 Forbidden, retrying (attempt 1 )...
[02:17:57] [udemy-downloader] [_get:874] ERROR: Failed request https://www.udemy.com/course/master-data-engineering-using-gcp-data-analytics/learn/
[02:17:57] [udemy-downloader] [_get:875] ERROR: 403 Forbidden, retrying (attempt 2 )...
Traceback (most recent call last):
  File "E:\Rizki\ITS\Udemy\udemy-downloader\main.py", line 1858, in <module>
    main()
  File "E:\Rizki\ITS\Udemy\udemy-downloader\main.py", line 1631, in main
    course_id, course_info = udemy._extract_course_info(course_url)
  File "E:\Rizki\ITS\Udemy\udemy-downloader\main.py", line 831, in _extract_course_info
    course_id, portal_name = self._extract_subscription_course_info(url)
  File "E:\Rizki\ITS\Udemy\udemy-downloader\main.py", line 780, in _extract_subscription_course_info
    course_html = self.session._get(url).text
AttributeError: 'NoneType' object has no attribute 'text'
```

### Expected Result

```
[01:40:35] [udemy-downloader] [__init__:331] INFO: Login Success
[01:40:35] [udemy-downloader] [main:1609] INFO: > Fetching course information, this may take a minute...
[01:40:36] [udemy-downloader] [main:1612] INFO: > Course information retrieved!
[01:40:36] [udemy-downloader] [main:1618] INFO: > Fetching course content, this may take a minute...
[01:40:36] [udemy-downloader] [main:1631] INFO: > Course content retrieved!
[01:40:36] [udemy-downloader] [main:1656] INFO: > Processing course data, this may take a minute. 
[01:40:36] [udemy-downloader] [main:1684] INFO: Processing 1 of 40
[01:40:36] [udemy-downloader] [main:1684] INFO: Processing 2 of 40
[01:40:36] [udemy-downloader] [main:1684] INFO: Processing 3 of 40
[01:40:36] [udemy-downloader] [main:1684] INFO: Processing 4 of 40
[01:40:36] [udemy-downloader] [main:1684] INFO: Processing 5 of 40
[01:40:36] [udemy-downloader] [main:1684] INFO: Processing 7 of 40
[01:40:36] [udemy-downloader] [main:1684] INFO: Processing 8 of 40
[01:40:36] [udemy-downloader] [main:1684] INFO: Processing 9 of 40
[01:40:36] [udemy-downloader] [main:1684] INFO: Processing 10 of 40
[01:40:36] [udemy-downloader] [main:1684] INFO: Processing 11 of 40
[01:40:36] [udemy-downloader] [main:1684] INFO: Processing 13 of 40
[01:40:36] [udemy-downloader] [main:1684] INFO: Processing 14 of 40
[01:40:36] [udemy-downloader] [main:1684] INFO: Processing 16 of 40
[01:40:36] [udemy-downloader] [main:1684] INFO: Processing 17 of 40
[01:40:36] [udemy-downloader] [main:1684] INFO: Processing 18 of 40
[01:40:36] [udemy-downloader] [main:1684] INFO: Processing 19 of 40
[01:40:36] [udemy-downloader] [main:1684] INFO: Processing 20 of 40
[01:40:36] [udemy-downloader] [main:1684] INFO: Processing 21 of 40
[01:40:36] [udemy-downloader] [main:1684] INFO: Processing 23 of 40
[01:40:36] [udemy-downloader] [main:1684] INFO: Processing 25 of 40
[01:40:36] [udemy-downloader] [main:1684] INFO: Processing 26 of 40
[01:40:36] [udemy-downloader] [main:1684] INFO: Processing 27 of 40
[01:40:36] [udemy-downloader] [main:1684] INFO: Processing 28 of 40
[01:40:36] [udemy-downloader] [main:1684] INFO: Processing 30 of 40
[01:40:36] [udemy-downloader] [main:1684] INFO: Processing 32 of 40
[01:40:36] [udemy-downloader] [main:1684] INFO: Processing 33 of 40
[01:40:36] [udemy-downloader] [main:1684] INFO: Processing 34 of 40
[01:40:36] [udemy-downloader] [main:1684] INFO: Processing 35 of 40
[01:40:36] [udemy-downloader] [main:1684] INFO: Processing 37 of 40
[01:40:36] [udemy-downloader] [main:1684] INFO: Processing 39 of 40
[01:40:36] [udemy-downloader] [_print_course_info:1510] INFO:
```

### Branch

master/main

### What operating systems are you seeing the problem on?

Windows

### Other information
I have successfully downloaded my purchased course but when i tried to download and get the information about course within my personal subscription there was an error with my above explanation.
**Expected result is from my purchased course.**

screenshot of my cookie:
![image](https://user-images.githubusercontent.com/74168801/230037076-eccba65f-af95-48c1-a9b5-539ce6e05958.png)

_No response_

**Comment by TriRizki** [comment]
It's my bad... 
for subscription course you have to use feat/cookies branch. master branch only for purchased course.
therefore this issue is fixed.
