### ISSUE TITLE
[Bug]: Muxing returned a non-zero exit code

### ISSUE THREAD

**Issue by jaan143** [Puyodead1/udemy-downloader#174]
### What happened?

the script is not deleting encrypted videos and keep both files enc and dec files

### Expected Result

i want that enc files must delete after dec 

### Branch

master/main

### What operating systems are you seeing the problem on?

Windows

### Relevant log output

```shell
[07:09:22] [udemy-downloader] [handle_segments:1358] INFO: > Merging video and audio, this might take a minute...
[07:09:22] [udemy-downloader] [handle_segments:1369] ERROR: Error: 
Traceback (most recent call last):
  File "C:\Users\hp\Downloads\udl\main.py", line 1359, in handle_segments
    mux_process(video_title, video_filepath_dec, audio_filepath_dec, output_path)
  File "C:\Users\hp\Downloads\udl\main.py", line 1190, in mux_process
    raise Exception("Muxing returned a non-zero exit code")
Exception: Muxing returned a non-zero exit code
```

**Comment by Puyodead1** [comment]
It doesn't delete them because there was an error. Post more of the log.

**Comment by jaan143** [comment]
@Puyodead1  whole log file have only this error after this

Decrypting video, this might take a minute...
[07:09:41] [udemy-downloader] [handle_segments:1351] INFO: > Dec complete
[07:09:41] [udemy-downloader] [handle_segments:1352] INFO: > Dec audio, this might take a minute...
[07:09:41] [udemy-downloader] [handle_segments:1357] INFO: > Dec complete
[07:09:41] [udemy-downloader] [handle_segments:1358] INFO: > Merging video and audio, this might take a minute...
[07:09:41] [udemy-downloader] [handle_segments:1369] ERROR: Error: 
Traceback (most recent call last):
  File "C:\Users\hp\Downloads\udl\main.py", line 1359, in handle_segments
    mux_process(video_title, video_filepath_dec, audio_filepath_dec, output_path)
  File "C:\Users\hp\Downloads\udl\main.py", line 1190, in mux_process
    raise Exception("Muxing returned a non-zero exit code")
Exception: Muxing returned a non-zero exit code

**Comment by jaan143** [comment]
@Puyodead1  problem is in ffmpeg is not set an internal or external command.
can you please help to add this path line in your script instead of set environment path ?

**Comment by jaan143** [comment]
it is already placed in the same folder ffmpeg.exe file

**Comment by Puyodead1** [comment]
> @Puyodead1  it is already placed in the same folder ffmpeg.exe file 

Then you will need to add it to the path.
