### ISSUE TITLE
[Bug]: URL and Part Files on lectures with special characters

### ISSUE THREAD

**Issue by DarkeCypher** [Puyodead1/udemy-downloader#182]
### What happened?

Some of the lectures with speacial characters in the name don't download properly. They download as URL and PART files. 

I have tried adding the following to main.py with no success:
```
        .replace(";", "")
        .replace(":", "")
        .replace("!", "")
        .replace("(", "")
        .replace(")", "")
        .replace("-", "")
        .replace("_", "")
```

### Expected Result

Video files instead of URL and PART Files.

### Branch

master/main

### What operating systems are you seeing the problem on?

Windows

### Relevant log output

```shell
File "C:\Users\[USERNAME]\Downloads\udemy-downloader-master\main.py", line 1550, in process_caption
    ret_code = download_aria(caption.get("download_url"), lecture_dir, filename)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[USERNAME]\Downloads\udemy-downloader-master\main.py", line 1536, in download_aria
    raise Exception("Return code from the downloader was non-0 (error)")
Exception: Return code from the downloader was non-0 (error)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\[USERNAME]\Downloads\udemy-downloader-master\main.py", line 1550, in process_caption
    ret_code = download_aria(caption.get("download_url"), lecture_dir, filename)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[USERNAME]\Downloads\udemy-downloader-master\main.py", line 1536, in download_aria
    raise Exception("Return code from the downloader was non-0 (error)")
Exception: Return code from the downloader was non-0 (error)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\[USERNAME]\Downloads\udemy-downloader-master\main.py", line 1562, in process_caption
    convert(lecture_dir, filename_no_ext)
  File "C:\Users\[USERNAME]\Downloads\udemy-downloader-master\vtt_to_srt.py", line 14, in convert
    for caption in WebVTT().read(vtt_filepath):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[USERNAME]\AppData\Local\Programs\Python\Python311\Lib\site-packages\webvtt\webvtt.py", line 60, in read
    parser = WebVTTParser().read(file)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[USERNAME]\AppData\Local\Programs\Python\Python311\Lib\site-packages\webvtt\parsers.py", line 24, in read
    content = self._get_content_from_file(file_path=file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[USERNAME]\AppData\Local\Programs\Python\Python311\Lib\site-packages\webvtt\parsers.py", line 38, in _get_content_from_file
    encoding = self._read_file_encoding(file_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[USERNAME]\AppData\Local\Programs\Python\Python311\Lib\site-packages\webvtt\parsers.py", line 43, in _read_file_encoding
    first_bytes = min(32, os.path.getsize(file_path))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 50, in getsize
```

**Comment by DarkeCypher** [comment]
Running the code in debug loggin mode returns state -1

**Comment by Puyodead1** [comment]
> Running the code in debug logging mode returns state -1

which special characters? can you post some example file names?
