### ISSUE TITLE
Udemy Says: 'NoneType' object has no attribute

### ISSUE THREAD

**Issue by parvinders347** [Puyodead1/udemy-downloader#195]
### What happened?

Why its giving me error im using cookies.txt
Python -v 3.11

Udemy Says: 'NoneType' object has no attribute 'content' on https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=500&search=how-to-start-a-youtube-automation-channel-monetize-it-fast

### Expected Result

Down... The Course

### Branch

feat-selenium

### What operating systems are you seeing the problem on?

Windows

**Comment by hughware** [comment]
I also encountered this situation
```bash
Arguments: ()
Traceback (most recent call last):
  File "D:\PycharmProjects\udemy-downloader\main.py", line 2066, in <module>
    main()
  File "D:\PycharmProjects\udemy-downloader\main.py", line 2059, in main
    parse_new(udemy, udemy_object)
  File "D:\PycharmProjects\udemy-downloader\main.py", line 1743, in parse_new
    parsed_lecture = udemy._parse_lecture(lecture)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PycharmProjects\udemy-downloader\main.py", line 1006, in _parse_lecture
    sources = self._extract_sources(sources, skip_hls)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PycharmProjects\udemy-downloader\main.py", line 523, in _extract_sources
    out = self._extract_m3u8(download_url)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PycharmProjects\udemy-downloader\main.py", line 587, in _extract_m3u8
    asset_id = asset_id_re.search(url).group("id")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'
(venv) PS D:\PycharmProjects\udemy-downloader> 
```

**Comment by Puyodead1** [comment]
use feat/refactor with the `--browser` option (see the readme in that branch)
