### ISSUE TITLE
[Bug]: No such file or directory: 'quiz_template.html'

### ISSUE THREAD

**Issue by bikash0070** [Puyodead1/udemy-downloader#206]
### What happened?

Getting error while downloading quiz

### Expected Result

Traceback (most recent call last):
  File "main.py", line 2066, in <module>
    main()
  File "main.py", line 2059, in main
    parse_new(udemy, udemy_object)
  File "main.py", line 1736, in parse_new
    process_quiz(udemy, lecture, chapter_dir)
  File "main.py", line 1664, in process_quiz
    process_normal_quiz(quiz, lecture, chapter_dir)
  File "main.py", line 1675, in process_normal_quiz
    with open("quiz_template.html", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'quiz_template.html'

### Branch

master/main

### What operating systems are you seeing the problem on?

Windows

### Relevant log output

```shell
[04:15:10] [udemy-downloader] [parse_new:1778] INFO: Processing 4 caption(s)...
[04:15:10] [udemy-downloader] [process_caption:1560] INFO:     >  Downloading caption: '006 How to Use this Video Course_en.vtt'
[04:15:10] [udemy-downloader] [process_caption:1573] INFO:     > Converting caption to SRT format...
[04:15:10] [udemy-downloader] [process_caption:1575] INFO:     > Caption conversion complete.
[04:15:10] [udemy-downloader] [parse_new:1786] INFO:     > Processing 0 asset(s) for lecture...
[04:15:10] [udemy-downloader] [parse_new:1727] INFO: ======= Processing chapter 2 of 23 =======
[04:15:12] [udemy-downloader] [parse_new:1754] INFO:   > Processing lecture 7 of 147
[04:15:12] [udemy-downloader] [parse_new:1758] INFO:       > Lecture '007 Tools of the Trade' is already downloaded, skipping...
[04:15:12] [udemy-downloader] [parse_new:1778] INFO: Processing 4 caption(s)...
[04:15:12] [udemy-downloader] [process_caption:1560] INFO:     >  Downloading caption: '007 Tools of the Trade_en.vtt'
[04:15:13] [udemy-downloader] [process_caption:1573] INFO:     > Converting caption to SRT format...
[04:15:13] [udemy-downloader] [process_caption:1575] INFO:     > Caption conversion complete.
[04:15:13] [udemy-downloader] [parse_new:1786] INFO:     > Processing 1 asset(s) for lecture...
[04:15:15] [udemy-downloader] [parse_new:1754] INFO:   > Processing lecture 8 of 147
[04:15:15] [udemy-downloader] [parse_new:1758] INFO:       > Lecture '008 Troubleshooting Theory' is already downloaded, skipping...
[04:15:15] [udemy-downloader] [parse_new:1778] INFO: Processing 4 caption(s)...
[04:15:15] [udemy-downloader] [process_caption:1560] INFO:     >  Downloading caption: '008 Troubleshooting Theory_en.vtt'
[04:15:15] [udemy-downloader] [process_caption:1573] INFO:     > Converting caption to SRT format...
[04:15:15] [udemy-downloader] [process_caption:1575] INFO:     > Caption conversion complete.
[04:15:15] [udemy-downloader] [parse_new:1786] INFO:     > Processing 0 asset(s) for lecture...
[04:15:15] [udemy-downloader] [process_normal_quiz:1673] INFO:   > Processing quiz 1
```

**Comment by Puyodead1** [comment]
You're missing a file... not a bug
