### ISSUE TITLE
[Bug]: Unknown command line flag 'enable_raw_key_decryption'

### ISSUE THREAD

**Issue by ahmed8aju** [Puyodead1/udemy-downloader#211]
### What happened?

[02:28:08] [udemy-downloader] [handle_segments:1425] INFO: > Lecture Tracks Downloaded
[02:28:08] [udemy-downloader] [handle_segments:1433] INFO: KID for video file is: 6EF42BC4115F481BA012B4DCEF68B5BA
[02:28:08] [udemy-downloader] [handle_segments:1440] INFO: KID for audio file is: 6EF42BC4115F481BA012B4DCEF68B5BA
[02:28:08] [udemy-downloader] [handle_segments:1446] INFO: > Decrypting video, this might take a minute...
ERROR: Unknown command line flag 'enable_raw_key_decryption'
ERROR: Unknown command line flag 'keys'. Did you mean: v ?
[02:28:08] [udemy-downloader] [handle_segments:1469] ERROR: Error:
Traceback (most recent call last):
  File "C:\Users\Downloads\udemy-downloader-master\main.py", line 1447, in handle_segments
    ret_code = decrypt(video_kid, video_filepath_enc, video_filepath_dec)
  File "C:\Users\Downloads\udemy-downloader-master\main.py", line 1310, in decrypt
    raise Exception("Decryption returned a non-zero exit code")
Exception: Decryption returned a non-zero exit code

### Expected Result

It should decrypted the files!

### Branch

master/main

### What operating systems are you seeing the problem on?

Windows

### Relevant log output

```shell
[02:28:08] [udemy-downloader] [handle_segments:1425] INFO: > Lecture Tracks Downloaded
[02:28:08] [udemy-downloader] [handle_segments:1433] INFO: KID for video file is: 6EF42BC4115F481BA012B4DCEF68B5BA
[02:28:08] [udemy-downloader] [handle_segments:1440] INFO: KID for audio file is: 6EF42BC4115F481BA012B4DCEF68B5BA
[02:28:08] [udemy-downloader] [handle_segments:1446] INFO: > Decrypting video, this might take a minute...
ERROR: Unknown command line flag 'enable_raw_key_decryption'
ERROR: Unknown command line flag 'keys'. Did you mean: v ?
[02:28:08] [udemy-downloader] [handle_segments:1469] ERROR: Error:
Traceback (most recent call last):
  File "C:\Users\Downloads\udemy-downloader-master\main.py", line 1447, in handle_segments
    ret_code = decrypt(video_kid, video_filepath_enc, video_filepath_dec)
  File "C:\Users\Downloads\udemy-downloader-master\main.py", line 1310, in decrypt
    raise Exception("Decryption returned a non-zero exit code")
Exception: Decryption returned a non-zero exit code
```

**Comment by Puyodead1** [comment]
shaka-packager is outdated.

**Comment by ahmed8aju** [comment]
Which version should I use?
Currently, I am using the v3.0.1 [Latest]

**Comment by ahmed8aju** [comment]
I tried 2.6.1 and still getting the same error!

**Comment by Puyodead1** [comment]
Then you are doing something wrong, cause it works fine.

**Comment by Puyodead1** [comment]
3.0.1 works fine also

**Comment by ahmed8aju** [comment]
I am not able to figure out, what I am doing wrong here. Where can I ask for assistance?

**Comment by ahmed8aju** [comment]
I tried explicitly...but getting below error
C:\Users\AijajA>shaka-packager.exe in='Frost.fvideo=3295464.mp4',stream=video,output=Frost.mp4 --enable_raw_key_decryption --keys key_id=c2471312525641a38487ac8adc5b6f37:key=94b0ba348ce2fa88049378987c462e18
ERROR: Unknown command line flag 'enable_raw_key_decryption'
ERROR: Unknown command line flag 'keys'. Did you mean: v ?
