### ISSUE TITLE
[Bug]: Assets can have the same name

### ISSUE THREAD

**Issue by moliberga** [Puyodead1/udemy-downloader#244]
### What happened?

![{AA58CBA2-127D-433D-9590-8467C13379EF}](https://github.com/user-attachments/assets/35ea1e1f-fc26-403c-bbec-25b5ec748c63)

```python
[04:52:16] [udemy-downloader] [parse_new:1725] ERROR: > Error downloading asset
Traceback (most recent call last):
  File "/udemy-downloader/main.py", line 1722, in parse_new
    ret_code = download_aria(download_url, chapter_dir, filename)
  File "/udemy-downloader/main.py", line 1417, in download_aria
    raise Exception("Return code from the downloader was non-0 (error)")
Exception: Return code from the downloader was non-0 (error)
```

### Expected Result

rename new download as (1)
example: abc.pdf, abc_1.pdf

### Branch

master/main

### What operating systems are you seeing the problem on?

Linux/Unix

**Comment by Puyodead1** [comment]
Are they not the same content?

**Comment by moliberga** [comment]
> Are they not the same content?

no. they are different files.
