### ISSUE TITLE
[Bug]: AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by swahpy** [Puyodead1/udemy-downloader#257]
### What happened?

During the downloading, an error occured: AttributeError: 'NoneType' object has no attribute 'group'. The url argument of function `_extract_m3u8` doesn't satisfy the pattern `assets/(?P<id>\d+)/`. The url actually is like `https://mp4-c.udemycdn.com/2023-11-17_19-41-30-8471b680e23e6a383a8cf7cc6144c473/2/WebHD_720p.mp4?xxxxxxx`

### Expected Result

downloading will continue.

### Branch

master/main

### What operating systems are you seeing the problem on?

Windows

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Users\hitwh\Documents\udemy\downloader-4db8cea\main.py", line 2010, in <module>
    main()
  File "C:\Users\hitwh\Documents\udemy\downloader-4db8cea\main.py", line 2001, in main
    parse_new(udemy, udemy_object)
  File "C:\Users\hitwh\Documents\udemy\downloader-4db8cea\main.py", line 1622, in parse_new
    parsed_lecture = udemy._parse_lecture(lecture)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hitwh\Documents\udemy\downloader-4db8cea\main.py", line 1012, in _parse_lecture
    sources = self._extract_sources(sources, skip_hls)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hitwh\Documents\udemy\downloader-4db8cea\main.py", line 598, in _extract_sources
    out = self._extract_m3u8(download_url)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hitwh\Documents\udemy\downloader-4db8cea\main.py", line 668, in _extract_m3u8
    asset_id = asset_id_re.search(url).group("id")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'
```

### Other information

the url argument in above case is `download url is:  https://mp4-c.udemycdn.com/2023-11-17_19-41-30-8471b680e23e6a383a8cf7cc6144c473/2/WebHD_720p.mp4?Expires=1732795834&Signature=nT6J5YoU9vViqzOHjKqu3CPZ12othcrhjnDFMYK6AH3OUEsjVQ~NEx0V5ugTDXg05l8L5p-htULzde~MvnB694rWHLfuLZBoRMeLxIlm3u8UNYiPDpc9zaa9P5TeLttj5585dFCFMrVFiLwWCbqolX-tO9NlAf5MlUucTtAfhDyX-5WUjP4Q~ySUjFfyLr0k9HMfU3w-wW89haE5F6Cc5AoeBiEsqETKEVbeRZpbJ1yl2zVVQp8bknZJ23JW~ttoWQE0DQLEi5FHnptIn43dGv4jCRB4mxxbqYr2-z~sGSu-P2mowLG19Eg8IZ52iYOvuHyxSMCzPlMEy1IX3LUAXA__&Key-Pair-Id=K3MG148K9RIRF4`.

**Comment by swahpy** [comment]
fixed by bypass the unexpected url.
