### ISSUE TITLE
Udemy Says: 403 Forbidden 

### ISSUE THREAD

**Issue by mahdisky** [Puyodead1/udemy-downloader#47]
hi
I tried very hard but everyone makes this mistakeو
" Udemy Says: 403 Forbidden "

**Comment by Puyodead1** [comment]
check your bearer token

**Comment by mahdisky** [comment]
i using bearer token but its show error

**Comment by amirali1996** [comment]
> i using bearer token but its show error

if you are from ME use US IP

**Comment by aluisco** [comment]
Same here:

(venv) root@DESKTOP-Q0SCQBM:/mnt/d/Projects/udemy-downloader# python main.py -c https://www.udemy.com/course/XXX
Login Success
> Fetching course information, this may take a minute...
Udemy Says: 403 Forbidden on https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=500&search=XXX

I think they disable the download option for now

**Comment by Puyodead1** [comment]
> I think they disable the download option for now

If that were the case, you wouldn't be able to use the website to view courses either. I'll take a look and see if I can find what's going on

**Comment by Puyodead1** [comment]
I just tested it and it worked fine for me, so there must be something that different with the way you are trying to download. maybe a vpn?

**Comment by gyurix** [comment]
This is a real issue and I have made a fix to this for an older version of the application.
Please refer to my Discord post @ https://discord.com/channels/844358207018893323/844358207018893326/874340558796103751

**Comment by mahdisky** [comment]
I using vpn but its not work

**Comment by gyurix** [comment]
Using or not using VPN won't change anything, unless you have a bad quality VPN (like a free VPN shared between a bunch of people or something like that). However for safety reasons I would suggest using the same IP for the downloader script as your IP was when you logged in to Udemy and ideally also changing the user-agent in the script to the exact same one as your browser.

**Comment by mahdisky** [comment]
how to change  user-agent in scripts?

**Comment by gyurix** [comment]
https://github.com/Puyodead1/udemy-downloader/blob/master/main.py#L30 change this line after downloading the project

**Comment by mahdisky** [comment]
i done it but its not work again

**Comment by Puyodead1** [comment]
> 
> 
> Using or not using VPN won't change anything, unless you have a bad quality VPN (like a free VPN shared between a bunch of people or something like that). However for safety reasons I would suggest using the same IP for the downloader script as your IP was when you logged in to Udemy and ideally also changing the user-agent in the script to the exact same one as your browser.

forgot that was for 4xx errors, thought it was 5xx for some reason. I'll go ahead and add your fix.

**Comment by 0x2f0713** [comment]
This error raise again

**Comment by Puyodead1** [comment]
> 
> 
> This error raise again

Are you using the latest version of the utility?

**Comment by 0x2f0713** [comment]
> > This error raise again
> 
> Are you using the latest version of the utility?

Yes, I just clone this repo

**Comment by atakurt034** [comment]
Yeah apparently they have updated it. I've tried to login and then logout of Udemy with vpn's and without and the bearer token now remains the same.

**Comment by johnny-aras** [comment]
I have the same error with an aditional message:
403 Forbidden, retrying (attempt 9 )...
Udemy Says: 'NoneType' object has no attribute 'json' on https://www.udemy.com/a
pi-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&p
age=1&page_size=500&search=<URL-to-the-specific-course>
I appreciate so much if someone has a solution. Thanks in advanced.

**Comment by Zeddex** [comment]
I have the same issue. Using the same IP to login and run the script

**Comment by xatsuriyo** [comment]
Looks like something change within Udemy API
got the error
![error-udemy-downloader](https://user-images.githubusercontent.com/28748867/131714850-f1197eb7-7c5a-4f08-a2ec-604dc0b4efb1.png)

**Comment by Puyodead1** [comment]
Just tested myself and am getting this error also, I will see if I can find out why

**Comment by Puyodead1** [comment]
This looks to be caused by a cookie ``__cf_bm`` which is a CloudFlare cookie related to anti-bot protection.
https://support.cloudflare.com/hc/en-us/articles/200170156-Understanding-the-Cloudflare-Cookies#12345681

I will try a possible to solution tomorrow.

**Comment by rvipinkumar** [comment]
I am getting a 502 Bad gateway error as well. Is it same as above? Any possible solution for it? 

![Capture](https://user-images.githubusercontent.com/70497055/132150813-a24ccb4a-1e66-40ad-96c3-0c1055878ed1.JPG)

**Comment by rvipinkumar** [comment]
Hello @Puyodead1, any updates on the errors?

**Comment by Zeddex** [comment]
I've found a solution - use https://www.udemy.com/coure-name/ instead of https://www.udemy.com/course/coure-name/

**Comment by tcortega** [comment]
> I've found a solution - use https://www.udemy.com/course-name/ instead of https://www.udemy.com/course/course-name/

Seems to work as a temporary fix until someone finds a way to bypass the cf cookies. Selenium is the way @Puyodead1

**Comment by jbauer2016** [comment]
How do you avoid the DRM problem?

Chapter(s) (16)
Lecture(s) (39)
======= Processing chapter 1 of 16 =======
  > Processing lecture 1 of 39
001 Introduction.mp4
      > Lecture '001 Introduction' is already downloaded, skipping...
======= Processing chapter 2 of 16 =======
  > Processing lecture 2 of 39
001 Introuction.mp4
      > Lecture '001 SAP Introuction' has DRM, attempting to download
> Downloading Lecture Tracks...
Traceback (most recent call last):
  File "C:\Users\usuario\Downloads\udemy-downloader-master\main.py", line 1730, in <module>
    parse_new(_udemy, quality, skip_lectures, dl_assets, dl_captions,
  File "C:\Users\usuario\Downloads\udemy-downloader-master\main.py", line 1152, in parse_new
    process_lecture(lecture, lecture_path, lecture_file_name,
  File "C:\Users\usuario\Downloads\udemy-downloader-master\main.py", line 1040, in process_lecture
    handle_segments(source.get("download_url"),
  File "C:\Users\usuario\Downloads\udemy-downloader-master\main.py", line 869, in handle_segments
    ret_code = subprocess.Popen([
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

C:\Users\usuario\Downloads\udemy-downloader-master>


@Zeddex works but DRM fail...help me?

Thanks

**Comment by Zeddex** [comment]
> How do you avoid the DRM problem?
> @Zeddex works but DRM fail...help me?

Just find this repo widevine-l3-guesser

**Comment by Puyodead1** [comment]
> How do you avoid the DRM problem?
> 
> 
> 
> Chapter(s) (16)
> 
> Lecture(s) (39)
> 
> ======= Processing chapter 1 of 16 =======
> 
>   > Processing lecture 1 of 39
> 
> 001 Introduction.mp4
> 
>       > Lecture '001 Introduction' is already downloaded, skipping...
> 
> ======= Processing chapter 2 of 16 =======
> 
>   > Processing lecture 2 of 39
> 
> 001 Introuction.mp4
> 
>       > Lecture '001 SAP Introuction' has DRM, attempting to download
> 
> > Downloading Lecture Tracks...
> 
> Traceback (most recent call last):
> 
>   File "C:\Users\usuario\Downloads\udemy-downloader-master\main.py", line 1730, in <module>
> 
>     parse_new(_udemy, quality, skip_lectures, dl_assets, dl_captions,
> 
>   File "C:\Users\usuario\Downloads\udemy-downloader-master\main.py", line 1152, in parse_new
> 
>     process_lecture(lecture, lecture_path, lecture_file_name,
> 
>   File "C:\Users\usuario\Downloads\udemy-downloader-master\main.py", line 1040, in process_lecture
> 
>     handle_segments(source.get("download_url"),
> 
>   File "C:\Users\usuario\Downloads\udemy-downloader-master\main.py", line 869, in handle_segments
> 
>     ret_code = subprocess.Popen([
> 
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 951, in __init__
> 
>     self._execute_child(args, executable, preexec_fn, close_fds,
> 
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1420, in _execute_child
> 
>     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
> 
> FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado
> 
> 
> 
> C:\Users\usuario\Downloads\udemy-downloader-master>
> 
> 
> 
> 
> 
> @Zeddex works but DRM fail...help me?
> 
> 
> 
> Thanks

You already opened an issue asking this, there's no reason to go to another unrelated issue to ask again.

**Comment by jbauer2016** [comment]
@Zeddex perfect but this error ...

  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

Can I be missing a new library in windows 10?

**Comment by Puyodead1** [comment]
> @Zeddex perfect but this error ...
> 
> 
> 
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 951, in __init__
> 
>     self._execute_child(args, executable, preexec_fn, close_fds,
> 
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1420, in _execute_child
> 
>     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
> 
> FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado
> 
> 
> 
> Can I be missing a new library in windows 10?
> 
> 

I'm going to assume you didn't read the readme and that you didn't rename the keyfile

**Comment by rvipinkumar** [comment]
@jbauer2016 Seems like you installed a python version which is not the normal python. Where did you installed this python from? The lib folder of the python installation should have subprocess.py library, which in your case is throwing some error. Install python from python.org, and try again.

**Comment by jbauer2016** [comment]
@rvipinkumar perfect

Although I have the keyid and the key, something keeps failing me, but I'll take it out

Thanks

**Comment by Puyodead1** [comment]
Seems this issue has popped up again and the workaround mentioned above is no longer working, I looked into this and the issue is now caused by a Clouflare hCaptcha being displayed. I am not able to bypass this even when trying to use browser automation such as selenium. At this time, there is no solution to this.

**Comment by mahdisky** [comment]
i have this issue too,
now all users have this issue or some users?

**Comment by cyanide-aoe2** [comment]
Have the issue as well. Finally got around to setting this up and bam.

**Comment by gauravkhadgi** [comment]
@Puyodead1 Did you find any solution?

**Comment by cyanide-aoe2** [comment]
yt-dlp is failing. check their repo as well.

**Comment by rvipinkumar** [comment]
> I upload the .mpd to my own web server

That was a nice trick!!! Thanks man! For all those who don't know how to start a web server, there is one in Python itself!!!

**Comment by diliproshitha** [comment]
> 
> 
> > Can anyone find a solution?
> 
> What Puyodead1 said here: [#47 (comment)](https://github.com/Puyodead1/udemy-downloader/issues/47#issuecomment-945713827) woks for me.
> 
> What I've done was:
> 
>     1. pip uninstall yt-dlp
> 
>     2. git clone yt-dlp
> 
>     3. edit master/yt_dlp/utils.py and remove line 1680 ('User-Agent': random_user_agent(),)
> 
>     4. compile and install following https://github.com/yt-dlp/yt-dlp#compile
> 
> 
> Then udemy-downloader works like a charm. Hope this helps.

Can you please explain how to install this? I copied compiled yt-dlp into /use/local/bin. But when running main.py I am getting `ModuleNotFoundError: No module named 'yt_dlp'` error.
