### ISSUE TITLE
[Bug]: TypeError: join() argument must be str, bytes, or os.PathLike object, not 'int'

### ISSUE THREAD

**Issue by Leftifield** [Puyodead1/udemy-downloader#81]
### What happened?

I see processing of chapters and lectures but this error appears:

TypeError: join() argument must be str, bytes, or os.PathLike object, not 'int'
Is because the course name consists of numbers only and isn't being parsed as string?
### Expected Result

out_dir created & files joined as mp4.

### Branch

id-as-course-name

### What operating systems are you seeing the problem on?

Windows

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Users\mark\Downloads\udemy-downloader-id-as-course-name\main.py", line 1794, in <module>
    parse_new(_udemy, quality, skip_lectures, dl_assets, dl_captions,
  File "C:\Users\mark\Downloads\udemy-downloader-id-as-course-name\main.py", line 1155, in parse_new
    course_dir = os.path.join(download_dir, course_name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\ntpath.py", line 117, in join
    genericpath._check_arg_types('join', path, *paths)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'int'
```

**Comment by Puyodead1** [comment]
I've just rebased the id-as-course-name branch, it now has a bunch of updates from the master branch. Please give the latest version of that branch a try and let me know if you continue to have this problem

**Comment by Puyodead1** [comment]
If you still have this issue, feel free to open a new issue or reopen this one
