### ISSUE TITLE
Error after processing

### ISSUE THREAD

**Issue by superman2197** [Puyodead1/udemy-downloader#87]
Hi Guys,

I am getting below error after the course is processed. How can we get this working?

[01:14:36] [udemy-downloader] [parse_new:1357] INFO: Chapter(s) (7)
[01:14:36] [udemy-downloader] [parse_new:1358] INFO: Lecture(s) (325)
[01:14:36] [udemy-downloader] [parse_new:1372] INFO: ======= Processing chapter 1 of 7 =======
[01:14:36] [udemy-downloader] [parse_new:1390] INFO:   > Processing lecture 1 of 325
[01:14:36] [udemy-downloader] [parse_new:1395] INFO:       > Lecture '001 Important Course Instructions' is already downloaded, skipping...
[01:14:36] [udemy-downloader] [parse_new:1372] INFO: ======= Processing chapter 2 of 7 =======
[01:14:36] [udemy-downloader] [parse_new:1390] INFO:   > Processing lecture 2 of 325
[01:14:36] [udemy-downloader] [process_lecture:1312] INFO:       > Lecture doesn't have DRM, attempting to download...
[01:14:36] [udemy-downloader] [process_lecture:1321] INFO:       ====== Selected quality: hls 1080
[01:14:36] [udemy-downloader] [process_lecture:1345] ERROR: >        Error downloading lecture: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\********\Downloads\udemy-downloader-master\main.py", line 1882, in <module>
    main()
  File "C:\Users\********\Downloads\udemy-downloader-master\main.py", line 1875, in main
    parse_new(_udemy)
  File "C:\Users\********\Downloads\udemy-downloader-master\main.py", line 1415, in parse_new
    process_lecture(lecture, lecture_path,
  File "C:\Users\********\Downloads\udemy-downloader-master\main.py", line 1346, in process_lecture
    raise e
  File "C:\Users\********\Downloads\udemy-downloader-master\main.py", line 1337, in process_lecture
    ret_code = subprocess.Popen(args).wait()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

C:\Users\********\Downloads\udemy-downloader-master>

**Comment by Puyodead1** [comment]
install yt-dlp as the README says

**Comment by superman2197** [comment]
Thank you!

But that is already installed. I installed everything mentioned in the "requirement.txt" file.

C:\Users\**********\Downloads\udemy-downloader-master>pip install yt-dlp
Requirement already satisfied: yt-dlp in c:\users\**********\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (2021.12.27)
Requirement already satisfied: mutagen in c:\users\**********\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from yt-dlp) (1.45.1)
Requirement already satisfied: pycryptodomex in c:\users\**********\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from yt-dlp) (3.12.0)
Requirement already satisfied: websockets in c:\users\**********\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from yt-dlp) (10.1)
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the 'C:\Users\**********\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.

C:\Users\**********\Downloads\udemy-downloader-master>

**Comment by Puyodead1** [comment]
> Thank you!
> 
> But that is already installed. I installed everything mentioned in the "requirement.txt" file.
> 
> C:\Users*_********\Downloads\udemy-downloader-master>pip install yt-dlp Requirement already satisfied: yt-dlp in c:\users*********_\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (2021.12.27) Requirement already satisfied: mutagen in c:\users*_********\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from yt-dlp) (1.45.1) Requirement already satisfied: pycryptodomex in c:\users*********_\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from yt-dlp) (3.12.0) Requirement already satisfied: websockets in c:\users*_********\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from yt-dlp) (10.1) WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available. You should consider upgrading via the 'C:\Users*********_\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.
> 
> C:\Users**********\Downloads\udemy-downloader-master>

its not part of the requirements.txt file as it can be installed as a standalone executable as well.

your python scripts folder needs to be in your system path also or the program can't execute it, as the README file says. I also don't really recommend using the Windows Store version of python.

**Comment by superman2197** [comment]
Got it.
Placed the binary in program main directory and its working.
I will remove the store version and move to the exe installation.

Thank you so much!

Happy new year!

**Comment by Puyodead1** [comment]
Good to hear, you're welcome. Happy new year to you as well!
