### ISSUE TITLE
[Bug]: after lecture 20 it stopped downloading 

### ISSUE THREAD

**Issue by sacsbrainz** [Puyodead1/udemy-downloader#93]
### What happened?

After lecture 20 it started downloading empty folders and some folders will just have only the srt 
No videos or assets 

This happened on both 
The `master branch` 
```
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```
and `feat-shaka branch `
![20220104_072105](https://user-images.githubusercontent.com/40229306/148017698-ca892b9b-f5d2-4792-871f-2df410bc9020.jpg)
![20220104_072029](https://user-images.githubusercontent.com/40229306/148017760-cc0b8ed3-d5ab-4971-8b9f-e788776d43bc.jpg)

### Expected Result

Supposed to download all chapters/lectures (folders)
With videos and resources and srt 

### Branch

master/main

### What operating systems are you seeing the problem on?

Linux/Unix

### Relevant log output

```shell
MASTER BRANCH 
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.


FEAT-SHAKA BRANCH 
Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
--- Logging error ---
Traceback (most recent call last):
  File "main.py", line 1443, in parse_new
    download_aria(download_url, chapter_dir,
  File "main.py", line 1236, in download_aria
    raise Exception("Download returned a non-zero exit code")
Exception: Download returned a non-zero exit code

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/home/.local/lib/python3.8/site-packages/coloredlogs/__init__.py", line 1140, in format
    return logging.Formatter.format(self, record)
  File "/usr/lib/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "main.py", line 1874, in <module>
    main()
  File "main.py", line 1630, in main
    parse_new(_udemy)
  File "main.py", line 1446, in parse_new
    logger.error("> Error downloading asset: ", e)
Message: '> Error downloading asset: '
Arguments: (Exception('Download returned a non-zero exit code'),)
--- Logging error ---
Traceback (most recent call last):
  File "main.py", line 1443, in parse_new
    download_aria(download_url, chapter_dir,
  File "main.py", line 1236, in download_aria
    raise Exception("Download returned a non-zero exit code")
Exception: Download returned a non-zero exit code

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "main.py", line 1874, in <module>
    main()
  File "main.py", line 1630, in main
    parse_new(_udemy)
  File "main.py", line 1446, in parse_new
    logger.error("> Error downloading asset: ", e)
Message: '> Error downloading asset: '
Arguments: (Exception('Download returned a non-zero exit code'),)
```

### Other information

This happened on both masters branch and feat-shaka branch

**Comment by sacsbrainz** [comment]
???

**Comment by Puyodead1** [comment]
I pushed a few bug fixes today that might resolve this, please try with the latest version of the master branch

**Comment by sacsbrainz** [comment]
I just tried it seems to be worse now
It actually passes chapter 20 but some folders are empty and now plenty videos are missing from chapter 1-20

**Comment by Puyodead1** [comment]
> I just tried it seems to be worse now It actually passes chapter 20 but some folders are empty and now plenty videos are missing from chapter 1-20

upload a log please using the latest version

**Comment by sacsbrainz** [comment]
I will update the script and try again

**Comment by sacsbrainz** [comment]
i will try the selenium version that seems like a good idea

**Comment by sacsbrainz** [comment]
will try out the updated master branch now

**Comment by sacsbrainz** [comment]
still same issue
log below

**Comment by Puyodead1** [comment]
Can you enable debug logging `--log-level DEBUG` and run the command again? This will output more information that can be useful to find the issue. Upload that log

**Comment by sacsbrainz** [comment]
ok
but this will take additions 3-5 hours to reach chapter 20+ which is where the issues is

**Comment by sacsbrainz** [comment]
i used
```--save-to-file
```

but the program is complete so i cant contiune with load from
i was thinking of editing the course_content.json or _udemy.json but its so unreadable and cluster

no way to select chapter to start from??

**Comment by Puyodead1** [comment]
> i used
> 
> ```--save-to-file```
> 
> 
> 
> but the program is complete so i cant contiune with load from
> 
> i was thinking of editing the course_content.json or _udemy.json but its so unreadable and clustered
> 
> 
> 
> no way to select chapter to start from??
> 
> 

You are correct in that you would have to edit _udemy.json, you can use http://jsonformatter.curiousconcept.com to format it, there's currently no built in way to skip ahead

**Comment by sacsbrainz** [comment]
ok on it

**Comment by sacsbrainz** [comment]
when am done editing the json can i copy an paste like that?
i used

JSON Template

3 Space Tab
JSON Specification
RFC 8259

**Comment by Puyodead1** [comment]
Yeah

**Comment by sacsbrainz** [comment]
```--log-level DEBUG``` doesnt work after editing the udemy.json
also i after editing the json i was getting 403
so i have to start all over

**Comment by Puyodead1** [comment]
The links expire after a certain amount of time, not sure how long but it's probably an hour

**Comment by sacsbrainz** [comment]
network is kinda poor now so i tried to use vps am getting 403 error

**Comment by Puyodead1** [comment]
I tested it with udemy already and it bypasses the captchas correctly. And I am sure it's caused by cloud flare because of you print the response text it's the html of a cloud flare captcha page

**Comment by sacsbrainz** [comment]
just lookin at your selenium branch
note that
undetected_chromedriver (uc) version of seleium gets detected by cloudflare

if you are sure cloudflare is the main reason behind the 403 error
to ensure you builds can bypass cloudflare test it on this url
https://nowsecure.nl

if you get a loop meaning you caught
i recommend you look at ichrome its the only automation programming that i have used that passes cloudflare without issues

note i have also tried to to add a few arguments still hit the 403
i also tried to forward a zyte proxy via gost still hit the 403
look into ichrome

**Comment by Puyodead1** [comment]
uc has worked perfectly in my tests with udemy and for the users that are already using that branch. Log the response text in the _get method of Session and see what it says

**Comment by sacsbrainz** [comment]
can i give you my login so you try from your end
from chapter 20 upwards

**Comment by Puyodead1** [comment]
Sure, you can email me at puyodead@protonmail.com

**Comment by sacsbrainz** [comment]
I have sent it

**Comment by Puyodead1** [comment]
I've pushed some fixes for the selenium branch, I have also tested the web development bootcamp course and it downloads correctly. Please give it a try, and also let me know if I have forgotten to address anything as I'm working on getting through multiple open issues.

**Comment by sacsbrainz** [comment]
Ok i will try it next 6 hours

**Comment by sacsbrainz** [comment]
hello is still didnt work
from chapter 5 has no video

i have sent the log to your email
